namespace Sf.EndpointAI.ControlServer;

internal static class ControlConsolePage
{
    public const string Html = """
        <!doctype html>
        <html lang="zh-CN">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width,initial-scale=1">
          <title>EndpointAIDLP 资产控制台</title>
          <style>
            :root{font-family:Segoe UI,Microsoft YaHei,sans-serif;color:#172033;background:#f4f6f9;line-height:1.45}
            *{box-sizing:border-box}body{margin:0}button,input,select{font:inherit}button{cursor:pointer}button:disabled{cursor:not-allowed;opacity:.55}.hidden{display:none!important}
            .shell{max-width:1440px;margin:0 auto;padding:24px}.surface{background:#fff;border:1px solid #dfe5ed;border-radius:12px;box-shadow:0 3px 14px #2030500d}
            .auth-view{min-height:80vh;display:grid;place-items:center}.auth-card{width:min(440px,100%);padding:28px}.auth-card h1{margin:0 0 8px}.auth-card p{margin:0 0 22px}
            .field{display:grid;gap:6px;margin-bottom:14px}.field label{font-size:13px;color:#536176}.field input,.toolbar input,.toolbar select{width:100%;border:1px solid #aeb9c9;border-radius:8px;padding:10px 12px;background:#fff;color:#172033}
            .field input:focus,.toolbar input:focus,.toolbar select:focus,button:focus-visible{outline:3px solid #9dc1ff;outline-offset:1px;border-color:#1d5fd1}
            .primary,.secondary,.danger-button{border-radius:8px;padding:9px 13px;white-space:nowrap}.primary{border:1px solid #1d5fd1;background:#1d5fd1;color:#fff}.secondary{border:1px solid #aeb9c9;background:#fff;color:#172033}.danger-button{border:1px solid #a72d3c;background:#a72d3c;color:#fff}
            button:active{transform:translateY(1px)}.auth-card .primary{width:100%;margin-top:4px}.message{min-height:22px;margin:12px 0 0!important;color:#536176}.message.error{color:#a11f30}
            .app-header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding-bottom:18px}.app-header h1{font-size:24px;margin:0}.app-message{color:#536176;text-align:right}.app-message.error{color:#a11f30}
            .cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.metric{padding:16px}.metric span{display:block;color:#536176}.metric b{display:block;font-size:28px;font-weight:600;margin-top:4px}
            .allowlist-panel{padding:16px;margin-bottom:18px}.allowlist-header,.allowlist-footer{display:flex;align-items:center;justify-content:space-between;gap:14px}.allowlist-header h2{font-size:18px;margin:0}.allowlist-title{display:grid;gap:3px}.allowlist-version{white-space:nowrap}.allowlist-form{display:grid;grid-template-columns:minmax(240px,1fr) auto;gap:10px;margin-top:14px}.allowlist-form input{width:100%;border:1px solid #aeb9c9;border-radius:8px;padding:10px 12px;background:#fff;color:#172033}.allowlist-form input:focus{outline:3px solid #9dc1ff;outline-offset:1px;border-color:#1d5fd1}.allowlist-entries{display:grid;margin:14px 0;border-top:1px solid #e6ebf2}.allowlist-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;padding:10px 0;border-bottom:1px solid #e6ebf2}.allowlist-row code{overflow-wrap:anywhere}.allowlist-empty{padding:16px 0;color:#667389}.allowlist-actions{display:flex;gap:8px}.dirty{color:#946000;font-weight:600}
            .list-panel{padding:16px}.toolbar{display:grid;grid-template-columns:minmax(240px,1fr) 180px auto;gap:10px;margin-bottom:14px}.table-wrap{width:100%}
            table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{text-align:left;padding:11px 10px;border-bottom:1px solid #e6ebf2;vertical-align:top;overflow-wrap:anywhere}th{font-size:13px;color:#536176;font-weight:600}td{font-size:14px}tbody tr:hover{background:#f7f9fc}
            .empty{padding:32px 16px;text-align:center;color:#667389}.status{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:3px 9px;font-size:12px;font-weight:600;background:#edf2f8;color:#455369}.status.ok{background:#e8f6ee;color:#116b3c}.status.warn{background:#fff4db;color:#875100}.status.bad{background:#fdecef;color:#9d2030}.ok-text{color:#147d46}.warn-text{color:#946000}.bad-text{color:#a11f30}.muted{color:#667389}.small{font-size:12px}.mono{font-family:Consolas,SFMono-Regular,monospace;overflow-wrap:anywhere}
            .detail-header{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:start;margin-bottom:16px}.detail-title{display:grid;gap:5px}.detail-title h2{margin:0;font-size:24px}.detail-meta{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.detail-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}
            .detail-freshness{display:flex;gap:10px;flex-wrap:wrap;color:#667389;font-size:12px}.stale-banner{margin:-4px 0 14px;padding:10px 12px;border:1px solid #e6c777;border-radius:8px;background:#fff8e6;color:#704500}
            .host-panel{padding:16px;margin-bottom:18px}.host-facts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.fact{display:grid;gap:4px;min-width:0}.fact-label{font-size:12px;color:#667389}.fact-value{overflow-wrap:anywhere}
            .detail-metrics{grid-template-columns:repeat(3,minmax(0,1fr))}.section-heading{display:flex;align-items:end;justify-content:space-between;gap:12px;margin:24px 0 10px}.section-heading h2,.section-heading h3{margin:0}.agent-list{display:grid;gap:14px}
            .agent-group{background:#fff;border:1px solid #dfe5ed;border-radius:12px;overflow:hidden}.agent-summary{padding:16px;display:grid;gap:13px}.agent-summary-top{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.agent-summary h3{margin:0 0 3px;font-size:18px}.agent-facts{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px}.agent-facts .fact{padding-top:9px;border-top:1px solid #edf0f4}
            .models{border-top:1px solid #dfe5ed}.model-cluster{border-bottom:1px solid #dfe5ed}.model-cluster:last-child{border-bottom:0}.model-cluster-title{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 16px;background:#f7f9fc}.model-cluster-title h4{margin:0;font-size:16px}.model-cluster-meta{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.model-row{display:grid;grid-template-columns:1fr .85fr 1.35fr 1.35fr .9fr 1.15fr;gap:10px;padding:12px 16px;border-top:1px solid #edf0f4;align-items:start}.model-head{padding-top:9px;padding-bottom:9px;background:#fff;color:#536176;font-size:12px;font-weight:600}.model-row.is-priority{box-shadow:inset 3px 0 #1d5fd1}.model-cell{min-width:0;overflow-wrap:anywhere}.model-cell[data-label]::before{display:none}.model-cell.endpoint-child{padding-left:14px;border-left:2px solid #dce7f8}.cell-stack{display:grid;gap:4px}.current-label{color:#1d5fd1;font-size:12px;font-weight:600}.inactive-label{color:#667389;font-size:12px;font-weight:600}.inactive-configs{border-top:1px solid #dfe5ed;background:#fbfcfe}.inactive-configs>summary{cursor:pointer;padding:12px 16px;color:#455369;font-weight:600}.inactive-configs[open]>summary{border-bottom:1px solid #dfe5ed}.inactive-configs .models{border-top:0}.inactive-configs .model-row.is-priority{box-shadow:none}.empty-config{padding:14px 16px;border-top:1px solid #dfe5ed;color:#667389}
            .secondary-info{display:grid;gap:12px;margin-top:18px}.secondary-info details{background:#fff;border:1px solid #dfe5ed;border-radius:12px;padding:0 16px}.secondary-info summary{cursor:pointer;font-weight:600;padding:14px 0}.runtime-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;padding:0 0 16px}.command-list{display:grid;gap:10px;padding-bottom:14px}.command-record{border:1px solid #e2e7ee;border-radius:10px;padding:12px;background:#fbfcfe}.command-record-head{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-bottom:12px}.command-record-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.audit-list{display:grid;gap:8px;padding-bottom:14px}.audit-row{display:grid;grid-template-columns:1.1fr 1fr 1fr 2fr;gap:10px;padding:10px 0;border-top:1px solid #edf0f4;overflow-wrap:anywhere}.audit-head{color:#536176;font-size:12px;font-weight:600}
            @media(max-width:1050px){.agent-facts{grid-template-columns:repeat(3,minmax(0,1fr))}.host-facts,.runtime-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
            @media(max-width:820px){
              .shell{padding:16px}.cards{grid-template-columns:repeat(2,minmax(0,1fr))}.toolbar{grid-template-columns:1fr 150px auto}.detail-header{grid-template-columns:1fr}.detail-actions{justify-content:flex-start}.allowlist-footer{align-items:flex-start;flex-direction:column}.allowlist-actions{width:100%;justify-content:flex-end}
              .model-head,.audit-head{display:none}.model-row,.audit-row,.command-record-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.model-cell[data-label]::before,.audit-cell[data-label]::before{content:attr(data-label);display:block;color:#667389;font-size:12px;margin-bottom:3px}.model-row{padding:14px 16px}.model-row+.model-row{border-top:6px solid #f4f6f9}
            }
            @media(max-width:620px){
              .shell{padding:12px}.app-header{align-items:flex-start;flex-direction:column}.app-message{text-align:left}.cards,.detail-metrics,.host-facts,.runtime-grid,.agent-facts{grid-template-columns:1fr 1fr}.toolbar,.allowlist-form{grid-template-columns:1fr}.toolbar button,.allowlist-form button{width:100%}.allowlist-header{align-items:flex-start;flex-direction:column}.allowlist-actions{display:grid;grid-template-columns:1fr 1fr}.allowlist-actions button{width:100%}
              table,thead,tbody,tr,th,td{display:block}thead{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}tbody{display:grid;gap:10px}tbody tr{border:1px solid #dfe5ed;border-radius:10px;padding:10px}tbody td{display:grid;grid-template-columns:105px minmax(0,1fr);gap:8px;border:0;padding:5px}tbody td::before{content:attr(data-label);color:#667389;font-size:12px}tbody tr:hover{background:#fff}
              .model-row,.audit-row,.command-record-grid{grid-template-columns:1fr}.detail-title h2{font-size:21px}.section-heading{align-items:flex-start;flex-direction:column}
            }
            @media(max-width:420px){.cards,.detail-metrics,.host-facts,.runtime-grid,.agent-facts{grid-template-columns:1fr}.detail-actions{display:grid;grid-template-columns:1fr;width:100%}.detail-actions button{width:100%}}
          </style>
        </head>
        <body><main class="shell">
          <section id="authView" class="auth-view">
            <form id="authForm" class="surface auth-card">
              <h1>EndpointAIDLP 资产控制台</h1>
              <p class="muted">使用管理员凭据连接控制服务。</p>
              <div class="field"><label for="token">管理员 Token</label><input id="token" type="password" autocomplete="current-password" required></div>
              <div class="field"><label for="actor">操作人工号</label><input id="actor" maxlength="64" autocomplete="username" required></div>
              <button class="primary" type="submit">登录</button>
              <p id="authMessage" class="message" role="alert"></p>
            </form>
          </section>

          <section id="appShell" class="hidden">
            <header class="app-header">
              <h1>EndpointAIDLP 资产控制台</h1>
              <div id="appMessage" class="app-message" role="status" aria-live="polite"></div>
            </header>

            <section id="listView">
              <div class="cards">
                <div class="surface metric"><span>终端总数</span><b id="total">0</b></div>
                <div class="surface metric"><span>在线</span><b id="online" class="ok-text">0</b></div>
                <div class="surface metric"><span>离线/陈旧</span><b id="offline" class="warn-text">0</b></div>
                <div class="surface metric"><span>代理已停用</span><b id="disabled">0</b></div>
              </div>
              <section class="surface allowlist-panel" aria-labelledby="allowlistHeading">
                <div class="allowlist-header">
                  <div class="allowlist-title"><h2 id="allowlistHeading">代理白名单</h2><span class="muted small">精确匹配 Base URL，命中后恢复原地址并绕过 EndpointAIDLP</span></div>
                  <span id="allowlistVersion" class="status allowlist-version">策略未加载</span>
                </div>
                <form id="allowlistForm" class="allowlist-form">
                  <input id="allowlistInput" aria-label="新增白名单 Base URL" maxlength="2048" placeholder="https://api.example.invalid/v1">
                  <button class="secondary" type="submit">添加地址</button>
                </form>
                <div id="allowlistEntries" class="allowlist-entries"></div>
                <div class="allowlist-footer">
                  <span id="allowlistState" class="muted small" role="status" aria-live="polite">允许 HTTP/HTTPS；不支持通配符、查询参数或 Fragment。</span>
                  <div class="allowlist-actions"><button id="reloadAllowlist" class="secondary" type="button">重新加载</button><button id="saveAllowlist" class="primary" type="button" disabled>保存并下发</button></div>
                </div>
              </section>
              <div class="surface list-panel">
                <div class="toolbar">
                  <input id="search" aria-label="搜索主机名或 Device ID" placeholder="搜索主机名或 Device ID">
                  <select id="state" aria-label="在线状态"><option value="">全部状态</option><option value="online">在线</option><option value="stale">陈旧</option><option value="offline">离线</option><option value="legacyClient">旧版客户端</option></select>
                  <button id="refreshList" class="secondary" type="button">刷新</button>
                </div>
                <div class="table-wrap">
                  <table aria-label="终端列表"><thead><tr><th style="width:19%">主机</th><th style="width:12%">客户端</th><th style="width:12%">在线状态</th><th style="width:9%">Agent</th><th style="width:10%">模型配置</th><th style="width:13%">代理状态</th><th style="width:17%">最后心跳</th><th style="width:8%">操作</th></tr></thead><tbody id="devices"></tbody></table>
                  <div id="deviceEmpty" class="empty hidden">没有符合条件的终端。</div>
                </div>
              </div>
            </section>

            <section id="detailView" class="hidden">
              <div class="detail-header">
                <div class="detail-title"><h2 id="detailHostname"></h2><div id="detailMeta" class="detail-meta"></div><div id="detailFreshness" class="detail-freshness"></div></div>
                <div class="detail-actions"><button id="backToList" class="secondary" type="button">返回终端列表</button><button id="refreshDetail" class="secondary" type="button">刷新详情</button><button id="disableProxy" class="danger-button" type="button">停用代理</button><button id="enableProxy" class="primary" type="button">重新启用</button></div>
              </div>
              <div id="detailStaleBanner" class="stale-banner hidden" role="status">数据已陈旧，当前配置可能不是终端最新状态。</div>
              <div id="hostPanel" class="surface host-panel"></div>
              <div class="cards detail-metrics">
                <div class="surface metric"><span>已发现 Agent</span><b id="detailAgentCount">0</b><small id="detailAgentNote" class="muted"></small></div>
                <div class="surface metric"><span>当前模型</span><b id="detailEndpointCount">0</b><small id="detailEndpointNote" class="muted"></small></div>
                <div class="surface metric"><span>本次启动请求</span><b id="detailRequestCount">0</b><small id="detailRequestNote" class="muted"></small></div>
              </div>
              <div class="section-heading"><h2>Agent 与模型代理关系</h2><span class="muted small">主区仅显示当前启用配置，未启用配置在 Agent 内折叠展示</span></div>
              <div id="agentGroups" class="agent-list"></div>
              <div id="secondaryInfo" class="secondary-info"></div>
            </section>
          </section>
        </main>
        <script>
          const $=id=>document.getElementById(id),DetailRefreshIntervalMilliseconds=15000;let devices=[],currentDevice=null,currentDetail=null,currentCommands=[],currentAudit=[],currentPolicy=null,allowlistDraft=[],allowlistDirty=false,commandCreateInFlight=false,detailRefreshTimer=null,detailFetchInFlight=null,lastDetailRevision=null,lastDetailRefreshAt=null,inactiveOpenKeys=new Set();
          $('token').value=sessionStorage.getItem('sf-admin-token')||'';$('actor').value=sessionStorage.getItem('sf-admin-actor')||'';
          function value(v,fallback='未提供'){return v===null||v===undefined||v===''?fallback:String(v)}
          function node(tag,cls='',content){const e=document.createElement(tag);if(cls)e.className=cls;if(content!==undefined)e.textContent=content;return e}
          function setText(id,v){$(id).textContent=value(v,'0')}
          function setAppMessage(message,error=false){$('appMessage').textContent=message||'';$('appMessage').classList.toggle('error',error)}
          function showLogin(message=''){stopDetailAutoRefresh();$('authView').classList.remove('hidden');$('appShell').classList.add('hidden');$('authMessage').textContent=message;$('authMessage').classList.toggle('error',!!message);currentDevice=null;currentDetail=null;currentCommands=[];currentAudit=[];lastDetailRevision=null}
          function showList(){stopDetailAutoRefresh();$('authView').classList.add('hidden');$('appShell').classList.remove('hidden');$('listView').classList.remove('hidden');$('detailView').classList.add('hidden');currentDevice=null;currentDetail=null;currentCommands=[];currentAudit=[];lastDetailRevision=null}
          function showDetailView(){$('authView').classList.add('hidden');$('appShell').classList.remove('hidden');$('listView').classList.add('hidden');$('detailView').classList.remove('hidden');startDetailAutoRefresh()}
          function headers(json=false){const h={Authorization:'Bearer '+$('token').value,'X-SF-Admin-Actor':$('actor').value||'admin-token'};if(json)h['Content-Type']='application/json';return h}
          async function api(path,options={}){const r=await fetch(path,{...options,headers:{...headers(!!options.body),...(options.headers||{})}});if(!r.ok){const body=await r.text();const error=new Error(body||('HTTP '+r.status));error.status=r.status;if(r.status===401||r.status===403)showLogin('登录已失效，请重新登录。');throw error}return r.status===204?null:r.json()}
          function statusClass(status){const s=String(status||'').toLowerCase();if(['online','enabled','listening','attached','succeeded','success','bypassed'].includes(s))return'ok';if(['stale','degraded','pending','discovered','neverobserved','unknown','legacyclient'].includes(s))return'warn';if(['offline','disabled','error','failed','noncompliant','unsupported','connectionfailed','routefailed','gatewayreachedwitherror','disablefailed','enablefailed'].includes(s))return'bad';return''}
          function statusLabel(status){const labels={online:'在线',stale:'陈旧',offline:'离线',legacyClient:'旧版客户端',enabled:'已启用',disabled:'已停用',disableFailed:'停用失败',enableFailed:'启用失败',listening:'监听正常',stopped:'已停止',starting:'启动中',degraded:'降级',unknown:'未知',attached:'已挂载',bypassed:'白名单直连',discovered:'已发现',pending:'待处理',restartRequired:'需重启',nonCompliant:'不合规',unsupported:'不支持',error:'错误',succeeded:'成功',gatewayReachedWithError:'网关返回错误',connectionFailed:'连接失败',routeFailed:'路由失败',allowlistBypassed:'白名单直连',neverObserved:'未观测请求',disableProxy:'停用代理',enableProxy:'重新启用',executing:'执行中',delivered:'已下发',expired:'已过期',cancelled:'已取消'};return labels[status]||value(status)}
          function badge(status,label){const result=node('span','status '+statusClass(status),label||statusLabel(status));if(status==='nonCompliant')result.title='当前配置未精确指向该配置身份的预期路由，或仍指向没有有效配置实体的本地代理地址。';return result}
          function localTime(v){if(!v)return'未提供';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString()}
          function onlineStateForDevice(device){const seen=new Date(device?.lastSeenAtUtc).getTime();if(!Number.isFinite(seen))return'offline';const interval=Math.min(3600,Math.max(15,Number(device.heartbeatIntervalSeconds)||60))*1000,elapsed=Date.now()-seen;if(elapsed<=interval*2+30000)return'online';return elapsed<=interval*5+30000?'stale':'offline'}
          function compactId(v){const s=value(v);return s.length>18?s.slice(0,8)+'...'+s.slice(-6):s}
          function td(v,label,cls=''){const e=node('td',cls,value(v));e.dataset.label=label;return e}
          async function connect(){const token=$('token').value.trim(),actor=$('actor').value.trim();if(!token||!actor){showLogin('请输入管理员 Token 和操作人工号。');return}sessionStorage.setItem('sf-admin-token',token);sessionStorage.setItem('sf-admin-actor',actor);$('authMessage').textContent='正在验证...';try{await Promise.all([loadDevices(),loadPolicy()]);showList();setAppMessage('');renderDevices()}catch(e){if(e.status!==401&&e.status!==403)showLogin('连接失败：'+e.message)}}
          async function loadDevices(){devices=await api('/admin/v1/devices');renderDevices()}
          function normalizeBaseUrl(raw){const text=raw.trim();if(!text||text.length>2048||text.includes('?')||text.includes('#'))throw new Error('请输入不含查询参数或 Fragment 的完整 HTTP/HTTPS Base URL。');let url;try{url=new URL(text)}catch{throw new Error('Base URL 格式无效。')}if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new Error('仅支持不含账号信息的 HTTP/HTTPS Base URL。');const path=url.pathname==='/'?'':url.pathname.replace(/\/+$/,'');return url.origin+path}
          function renderAllowlist(){const root=$('allowlistEntries');root.replaceChildren();if(!allowlistDraft.length)root.append(node('div','allowlist-empty','当前没有白名单地址，所有 Base URL 都将按策略接入代理。'));for(const url of allowlistDraft){const row=node('div','allowlist-row');row.append(node('code','mono small',url));const remove=node('button','secondary','删除');remove.type='button';remove.setAttribute('aria-label','删除白名单 '+url);remove.onclick=()=>{allowlistDraft=allowlistDraft.filter(item=>item!==url);allowlistDirty=true;renderAllowlist()};row.append(remove);root.append(row)}$('allowlistVersion').textContent=currentPolicy?'策略 v'+currentPolicy.policyVersion:'策略未加载';$('saveAllowlist').disabled=!currentPolicy||!allowlistDirty;$('allowlistState').textContent=allowlistDirty?'有未保存的白名单变更':'允许 HTTP/HTTPS；不支持通配符、查询参数或 Fragment。';$('allowlistState').className=(allowlistDirty?'dirty':'muted')+' small'}
          async function loadPolicy(){currentPolicy=await api('/admin/v1/policy');allowlistDraft=[...(currentPolicy.allowlistedBaseUrls===null||currentPolicy.allowlistedBaseUrls===undefined?['https://ccr.example.invalid']:currentPolicy.allowlistedBaseUrls)];allowlistDirty=false;renderAllowlist()}
          function addAllowlistEntry(){try{const normalized=normalizeBaseUrl($('allowlistInput').value);if(allowlistDraft.includes(normalized)){setAppMessage('该 Base URL 已在白名单中',true);return}if(allowlistDraft.length>=256){setAppMessage('白名单最多允许 256 条地址',true);return}allowlistDraft.push(normalized);allowlistDirty=true;$('allowlistInput').value='';renderAllowlist();setAppMessage('')}catch(e){setAppMessage(e.message,true)}}
          async function saveAllowlist(){if(!currentPolicy||!allowlistDirty)return;$('saveAllowlist').disabled=true;setAppMessage('正在保存白名单...');try{const payload={expectedVersion:currentPolicy.policyVersion,enabled:currentPolicy.enabled,routeMode:currentPolicy.routeMode,gatewayOrigin:currentPolicy.gatewayOrigin,allowInsecureGateway:currentPolicy.allowInsecureGateway,pollIntervalSeconds:currentPolicy.pollIntervalSeconds,heartbeatIntervalSeconds:currentPolicy.heartbeatIntervalSeconds,allowlistedBaseUrls:allowlistDraft};currentPolicy=await api('/admin/v1/policy',{method:'PUT',body:JSON.stringify(payload)});allowlistDraft=[...(currentPolicy.allowlistedBaseUrls||[])];allowlistDirty=false;renderAllowlist();setAppMessage('白名单已保存为策略 v'+currentPolicy.policyVersion+'，终端将在下次同步后立即校准')}catch(e){if(e.status===409){await loadPolicy();setAppMessage('策略已被其他管理员更新，已重新加载，请确认后重试',true)}else if(e.status!==401&&e.status!==403){renderAllowlist();setAppMessage('白名单保存失败：'+e.message,true)}}}
          async function reloadAllowlist(){if(allowlistDirty&&!confirm('放弃未保存的白名单变更？'))return;setAppMessage('正在重新加载白名单...');try{await loadPolicy();setAppMessage('白名单已重新加载')}catch(e){if(e.status!==401&&e.status!==403)setAppMessage('白名单加载失败：'+e.message,true)}}
          function renderDevices(){const q=$('search').value.trim().toLowerCase(),state=$('state').value;const list=devices.filter(d=>(!q||String(d.hostname).toLowerCase().includes(q)||String(d.deviceId).toLowerCase().includes(q))&&(!state||d.onlineState===state));setText('total',devices.length);setText('online',devices.filter(d=>d.onlineState==='online').length);setText('offline',devices.filter(d=>d.onlineState==='stale'||d.onlineState==='offline').length);setText('disabled',devices.filter(d=>d.operationState==='disabled').length);const body=$('devices');body.replaceChildren();for(const d of list){const tr=node('tr');tr.append(td(d.hostname,'主机'),td(d.serviceVersion,'客户端'),td(statusLabel(d.onlineState),'在线状态',statusClass(d.onlineState)+'-text'),td(d.agentCount,'Agent'),td(d.endpointCount,'模型配置'),td(statusLabel(d.operationState),'代理状态',statusClass(d.operationState)+'-text'),td(localTime(d.lastSeenAtUtc),'最后心跳'));const action=node('td');action.dataset.label='操作';const button=node('button','secondary','详情');button.type='button';button.onclick=()=>openDetail(d);action.append(button);tr.append(action);body.append(tr)}$('deviceEmpty').classList.toggle('hidden',list.length!==0)}
          function familyForAgent(type){const t=String(type||'').toLowerCase();if(t.startsWith('claude'))return'claude';if(t.startsWith('codex'))return'codex';if(t.startsWith('qoder'))return'qoder';return null}
          function isCcSwitchAgent(agent){return String(agent?.agentType||'').toLowerCase()==='ccswitch'}
          function isSuspectedAgent(agent){return String(agent?.agentType||'').toLowerCase()==='unknowncandidate'}
          function confirmedAgents(detail){return(detail.agents||[]).filter(agent=>!isCcSwitchAgent(agent)&&!isSuspectedAgent(agent)&&familyForAgent(agent.agentType))}
          function logicalEndpointKey(endpoint){return[endpoint.userSid,endpoint.agentFamily,endpoint.configurationSource,endpoint.providerId||'',endpoint.endpointId||''].join('|')}
          function endpointRank(endpoint){return Number(!!endpoint.localRouteUrl)*8+Number(isEndpointIssue(endpoint))*4+Number(!!endpoint.isCurrent)*2+Number(endpoint.routeStatus==='attached')}
          function mergeEndpointObservations(endpoints){const grouped=new Map();for(const endpoint of endpoints||[]){const key=logicalEndpointKey(endpoint);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(endpoint)}const merged=[];for(const observations of grouped.values()){const isCurrent=observations.some(item=>item.isCurrent),eligible=isCurrent?observations.filter(item=>item.isCurrent):observations,ranked=[...eligible].sort((a,b)=>endpointRank(b)-endpointRank(a));const result={...ranked[0],assetIds:observations.map(item=>item.assetId),isCurrent};for(const property of['configuredModel','wireApi','originalTargetBaseUrl','effectiveConfiguredBaseUrl','localRouteUrl']){if(!result[property])result[property]=eligible.map(item=>item[property]).find(Boolean)||null}const severity={error:8,nonCompliant:7,unsupported:6,restartRequired:5,pending:4,bypassed:3,attached:2,discovered:1};result.routeStatus=[...eligible].sort((a,b)=>(severity[b.routeStatus]||0)-(severity[a.routeStatus]||0))[0].routeStatus;merged.push(result)}return merged}
          function familyLabel(family){return{claude:'Claude',codex:'Codex',qoder:'Qoder'}[family]||value(family)}
          function groupAssets(detail){const endpointGroups=new Map(),agentGroups=new Map(),components=(detail.agents||[]).filter(isCcSwitchAgent);for(const endpoint of mergeEndpointObservations(detail.endpoints)){const key=endpoint.userSid+'|'+endpoint.agentFamily;if(!endpointGroups.has(key))endpointGroups.set(key,[]);endpointGroups.get(key).push(endpoint)}for(const agent of confirmedAgents(detail)){const family=familyForAgent(agent.agentType),key=agent.userSid+'|'+family;if(!agentGroups.has(key))agentGroups.set(key,[]);agentGroups.get(key).push(agent)}const groups=[];for(const [key,endpoints] of endpointGroups){const split=key.indexOf('|'),userSid=key.slice(0,split);groups.push({key,family:key.slice(split+1),userSid,agents:agentGroups.get(key)||[],components:components.filter(item=>item.userSid===userSid),endpoints})}for(const [key,agents] of agentGroups)if(!endpointGroups.has(key)){const split=key.indexOf('|'),userSid=key.slice(0,split);groups.push({key,family:key.slice(split+1),userSid,agents,components:components.filter(item=>item.userSid===userSid),endpoints:[]})}return groups.sort((a,b)=>Number(b.endpoints.some(e=>e.isCurrent))-Number(a.endpoints.some(e=>e.isCurrent))||a.key.localeCompare(b.key))}
          function sourceLabel(source){return{direct:'Direct',ccSwitchProvider:'CC Switch Provider',ccSwitchEndpoint:'CC Switch Endpoint',unknown:'未知'}[source]||value(source)}
          function wireLabel(wire){return{anthropicMessages:'Anthropic Messages',openAiResponses:'OpenAI Responses',chatCompletions:'Chat Completions',unknown:'未知'}[wire]||value(wire)}
          function proxyMethod(endpoint){if(endpoint.allowlistBypassed)return'白名单直连';if(endpoint.localRouteUrl&&String(endpoint.configurationSource).startsWith('ccSwitch'))return'CC Switch + EndpointAIDLP';if(endpoint.localRouteUrl)return'EndpointAIDLP 本地代理';if(String(endpoint.configurationSource).startsWith('ccSwitch'))return'CC Switch';if(endpoint.effectiveConfiguredBaseUrl)return'未接入本地代理';return'未配置'}
          function isEndpointIssue(endpoint,activity){return!!endpoint?.isCurrent&&(['nonCompliant','unsupported','error','pending','restartRequired'].includes(endpoint.routeStatus)||['gatewayReachedWithError','connectionFailed','routeFailed'].includes(activity?.state))}
          function summarizeAgent(group){if(group.agents.length)return group.agents.map(a=>a.displayName).join(' / ');return familyLabel(group.family)+' 配置（未发现运行实例）'}
          function unique(values){return[...new Set(values.filter(Boolean))]}
          function addFact(root,label,content,cls=''){const wrap=node('div','fact');wrap.append(node('span','fact-label',label),node('span','fact-value '+cls,value(content)));root.append(wrap)}
          function renderHostPanel(device,detail){const root=$('hostPanel');root.replaceChildren();const facts=node('div','host-facts');addFact(facts,'Device ID',device.deviceId,'mono');addFact(facts,'客户端版本',device.serviceVersion);addFact(facts,'最后心跳',localTime(device.lastSeenAtUtc));addFact(facts,'服务启动时间',localTime(detail.runtime?.serviceStartedAtUtc));addFact(facts,'在线状态',statusLabel(device.onlineState),statusClass(device.onlineState)+'-text');addFact(facts,'代理状态',statusLabel(detail.runtime?.operationState||device.operationState),statusClass(detail.runtime?.operationState||device.operationState)+'-text');addFact(facts,'代理监听',detail.runtime?.proxyListenerAvailable?'可用':'不可用',detail.runtime?.proxyListenerAvailable?'ok-text':'bad-text');addFact(facts,'最近配置校准',detail.runtime?.lastReconcileResult||'未执行',detail.runtime?.lastReconcileResult==='SUCCESS'?'ok-text':'warn-text');root.append(facts)}
          function renderActivity(endpoint,activity){const root=node('div','cell-stack');const state=activity?.state||(endpoint.allowlistBypassed?'allowlistBypassed':'neverObserved');root.append(badge(state));const parts=[];if(activity?.requestCountSinceBoot!==undefined)parts.push('请求 '+activity.requestCountSinceBoot);if(activity?.successCountSinceBoot)parts.push('成功 '+activity.successCountSinceBoot);if(activity?.failureCountSinceBoot)parts.push('失败 '+activity.failureCountSinceBoot);if(activity?.lastHttpStatusCode)parts.push('HTTP '+activity.lastHttpStatusCode);if(activity?.lastGatewayRoundTripMilliseconds!==null&&activity?.lastGatewayRoundTripMilliseconds!==undefined)parts.push(activity.lastGatewayRoundTripMilliseconds+' ms');if(parts.length)root.append(node('span','small muted',parts.join(' · ')));if(activity?.lastRequestAtUtc)root.append(node('span','small muted','最近 '+localTime(activity.lastRequestAtUtc)));return root}
          function activityForEndpoint(endpoint,activityById){return(endpoint.assetIds||[endpoint.assetId]).map(id=>activityById.get(id)).filter(Boolean).sort((a,b)=>(b.requestCountSinceBoot||0)-(a.requestCountSinceBoot||0)||String(b.lastRequestAtUtc||'').localeCompare(String(a.lastRequestAtUtc||'')))[0]}
          function modelCell(label){const cell=node('div','model-cell');cell.dataset.label=label;return cell}
          function ccSwitchDescription(group){const component=group.components?.[0];if(!component)return null;const parts=['CC Switch'];if(component.version)parts.push('v'+component.version);if(component.ccSwitchMode)parts.push(component.ccSwitchMode);parts.push(component.running?'运行中':'未运行');return parts.join(' · ')}
          function renderModelRow(endpoint,activity,group,inactive=false){const row=node('div','model-row'+(!inactive&&(endpoint.isCurrent||isEndpointIssue(endpoint,activity))?' is-priority':''));const source=modelCell('配置来源');if(endpoint.endpointId)source.classList.add('endpoint-child');source.append(node('div','',endpoint.endpointId?'↳ CC Switch Endpoint':sourceLabel(endpoint.configurationSource)));source.append(node('div',inactive?'inactive-label':'current-label',inactive?'未启用':'当前配置'));if(endpoint.providerId)source.append(node('div','small muted','Provider '+compactId(endpoint.providerId)));if(endpoint.endpointId)source.append(node('div','small muted','Endpoint '+endpoint.endpointId));if(String(endpoint.configurationSource).startsWith('ccSwitch')){const description=ccSwitchDescription(group);if(description)source.append(node('div','small muted',description))}const wire=modelCell('协议');wire.append(node('div','',wireLabel(endpoint.wireApi)));const original=modelCell('原始目标 Base URL');original.append(node('div','mono small',value(endpoint.originalTargetBaseUrl)));const effective=modelCell('实际配置 / 代理 Base URL');effective.append(node('div','mono small',value(endpoint.effectiveConfiguredBaseUrl)));if(endpoint.localRouteUrl&&endpoint.localRouteUrl!==endpoint.effectiveConfiguredBaseUrl)effective.append(node('div','mono small muted','本地路由 '+endpoint.localRouteUrl));const route=modelCell('路由状态');route.append(badge(endpoint.routeStatus));route.append(node('div','small muted',proxyMethod(endpoint)));const result=modelCell('真实请求结果');result.append(renderActivity(endpoint,activity));row.append(source,wire,original,effective,route,result);return row}
          function groupModels(endpoints){const groups=new Map();for(const endpoint of endpoints){const model=String(endpoint.configuredModel||'').trim()||'未提供模型';if(!groups.has(model))groups.set(model,[]);groups.get(model).push(endpoint)}return[...groups].map(([model,items])=>({model,items})).sort((a,b)=>Number(b.items.some(e=>e.isCurrent))-Number(a.items.some(e=>e.isCurrent))||a.model.localeCompare(b.model))}
          function renderModelClusters(endpoints,activityById,group,inactive=false){const models=node('div','models');for(const modelGroup of groupModels(endpoints)){const cluster=node('section','model-cluster');const clusterTitle=node('div','model-cluster-title');clusterTitle.append(node('h4','',modelGroup.model));const clusterMeta=node('div','model-cluster-meta');clusterMeta.append(badge(inactive?'discovered':'attached',modelGroup.items.length+' 个配置关系'));clusterTitle.append(clusterMeta);cluster.append(clusterTitle);const head=node('div','model-row model-head');for(const label of['配置来源','协议','原始目标 Base URL','实际配置 / 代理 Base URL','路由状态','真实请求结果'])head.append(node('div','',label));cluster.append(head);const sorted=modelGroup.items.map(endpoint=>({endpoint,activity:activityForEndpoint(endpoint,activityById)})).sort((a,b)=>Number(isEndpointIssue(b.endpoint,b.activity))-Number(isEndpointIssue(a.endpoint,a.activity))||String(a.endpoint.endpointId||'').localeCompare(String(b.endpoint.endpointId||'')));for(const item of sorted)cluster.append(renderModelRow(item.endpoint,item.activity,group,inactive));models.append(cluster)}return models}
          function rememberInactiveOpenState(){for(const details of $('agentGroups').querySelectorAll('details[data-inactive-key]')){if(details.open)inactiveOpenKeys.add(details.dataset.inactiveKey);else inactiveOpenKeys.delete(details.dataset.inactiveKey)}}
          function renderAgentGroup(group,activityById){const ccSwitchOwned=group.endpoints.some(endpoint=>String(endpoint.configurationSource).startsWith('ccSwitch')),visibleEndpoints=group.endpoints.filter(endpoint=>!(ccSwitchOwned&&endpoint.configurationSource==='direct')),currentEndpoints=visibleEndpoints.filter(endpoint=>endpoint.isCurrent),inactiveEndpoints=visibleEndpoints.filter(endpoint=>!endpoint.isCurrent),section=node('section','agent-group'),summary=node('div','agent-summary'),top=node('div','agent-summary-top'),title=node('div');title.append(node('h3','',summarizeAgent(group)),node('div','small muted','用户 '+compactId(group.userSid)));const running=group.agents.some(agent=>agent.running),state=currentEndpoints.length?'attached':running?'online':'discovered',stateText=currentEndpoints.length?'存在当前配置':inactiveEndpoints.length?'仅有未启用配置':running?'正在运行':'仅发现';top.append(title,badge(state,stateText));summary.append(top);const facts=node('div','agent-facts'),versions=unique(group.agents.map(agent=>agent.version)),installs=unique(group.agents.map(agent=>agent.installMethod)),runCount=group.agents.filter(agent=>agent.running).length,routes=unique([...group.agents.map(agent=>statusLabel(agent.routeStatus)),...currentEndpoints.map(endpoint=>statusLabel(endpoint.routeStatus))]),methods=unique(currentEndpoints.map(proxyMethod));addFact(facts,'版本',versions.join(' / ')||'未提供');addFact(facts,'安装方式',installs.join(' / ')||'未提供');addFact(facts,'运行实例',group.agents.length?runCount+' / '+group.agents.length:'未发现');addFact(facts,'代理方式',methods.join(' / ')||'未配置');addFact(facts,'路由状态',routes.join(' / ')||'未提供');summary.append(facts);section.append(summary);if(currentEndpoints.length)section.append(renderModelClusters(currentEndpoints,activityById,group));else section.append(node('div','empty-config',inactiveEndpoints.length?'当前没有启用的模型配置。':'未发现可关联的模型、Provider 或 Base URL 配置。'));if(inactiveEndpoints.length){const inactive=node('details','inactive-configs');inactive.dataset.inactiveKey=group.key;inactive.open=inactiveOpenKeys.has(group.key);inactive.append(node('summary','','未启用配置（'+inactiveEndpoints.length+' 个关系）'),renderModelClusters(inactiveEndpoints,activityById,group,true));inactive.ontoggle=()=>{if(inactive.open)inactiveOpenKeys.add(group.key);else inactiveOpenKeys.delete(group.key)};section.append(inactive)}return section}
          function renderSecondaryInfo(detail,commands,audit){const root=$('secondaryInfo');root.replaceChildren();const suspected=(detail.agents||[]).filter(isSuspectedAgent);if(suspected.length){const candidates=node('details');candidates.append(node('summary','','疑似 Agent（'+suspected.length+'）'));const list=node('div','runtime-grid');for(const agent of suspected)addFact(list,agent.displayName||'疑似 Agent','置信度 '+value(agent.confidence)+' · '+(agent.running?'正在运行':'未发现运行实例'));candidates.append(list);root.append(candidates)}const runtime=node('details');runtime.append(node('summary','','终端运行状态'));const runtimeGrid=node('div','runtime-grid');addFact(runtimeGrid,'运行时长',detail.runtime?detail.runtime.uptimeSeconds+' 秒':'未提供');addFact(runtimeGrid,'最近控制同步',localTime(detail.runtime?.lastControlSyncAtUtc));addFact(runtimeGrid,'最近配置校准',localTime(detail.runtime?.lastReconcileAtUtc));addFact(runtimeGrid,'校准错误码',detail.runtime?.lastReconcileErrorCode||'无');runtime.append(runtimeGrid);root.append(runtime);const commandBox=node('details');commandBox.open=commands.some(command=>!['succeeded','failed','expired','cancelled'].includes(command.status));commandBox.append(node('summary','','远程命令记录（'+commands.length+'）'));if(!commands.length)commandBox.append(node('div','empty-config','暂无远程命令记录。'));else{const list=node('div','command-list');for(const command of commands){const record=node('article','command-record'),head=node('div','command-record-head'),identity=node('div','cell-stack');identity.append(node('b','',statusLabel(command.type)),node('span','mono small',command.commandId));head.append(identity,badge(command.status));record.append(head);const grid=node('div','command-record-grid');for(const [label,content,cls] of [['创建人',command.createdBy],['原因',command.reason],['创建时间',localTime(command.createdAtUtc)],['投递时间',localTime(command.deliveredAtUtc)],['开始时间',localTime(command.startedAtUtc)],['完成时间',localTime(command.completedAtUtc)],['结果码',command.resultCode||'无','mono'],['结果摘要',command.resultSummary||'无'],['投递次数',command.deliveryCount]])addFact(grid,label,content,cls||'');record.append(grid);list.append(record)}commandBox.append(list)}root.append(commandBox);const auditBox=node('details');auditBox.append(node('summary','','命令审计（'+audit.length+'）'));if(!audit.length)auditBox.append(node('div','empty-config','暂无命令创建、拒绝或取消审计。'));else{const list=node('div','audit-list'),head=node('div','audit-row audit-head');for(const label of['时间 / 操作人','动作','Command ID','摘要'])head.append(node('div','',label));list.append(head);for(const item of audit){const row=node('div','audit-row');for(const [label,content,cls] of [['时间 / 操作人',localTime(item.occurredAtUtc)+' · '+item.actor],['动作',item.action],['Command ID',item.commandId||'无','mono'],['摘要',item.summary]]){const cell=node('div','audit-cell '+(cls||''),value(content));cell.dataset.label=label;row.append(cell)}list.append(row)}auditBox.append(list)}root.append(auditBox)}
          function configurationEndpoints(group){const ccSwitchOwned=group.endpoints.some(endpoint=>String(endpoint.configurationSource).startsWith('ccSwitch'));return group.endpoints.filter(endpoint=>!(ccSwitchOwned&&endpoint.configurationSource==='direct'))}
          function collectedAt(detail){const candidates=[detail?.device?.lastSeenAtUtc,...(detail?.agents||[]).map(agent=>agent.lastSeenAtUtc),...(detail?.endpoints||[]).map(endpoint=>endpoint.observedAtUtc)].map(value=>new Date(value).getTime()).filter(Number.isFinite);return candidates.length?new Date(Math.max(...candidates)):null}
          function renderFreshness(){const root=$('detailFreshness');if(!root)return;root.replaceChildren(node('span','','数据采集时间 '+localTime(collectedAt(currentDetail))),node('span','','页面刷新时间 '+localTime(lastDetailRefreshAt)));const seen=new Date(currentDevice?.lastSeenAtUtc).getTime(),interval=Math.min(3600,Math.max(15,Number(currentDevice?.heartbeatIntervalSeconds)||60))*1000,stale=!Number.isFinite(seen)||Date.now()-seen>interval*2+30000;$('detailStaleBanner').classList.toggle('hidden',!stale)}
          function detailRevision(detail,commands,audit){return[detail?.device?.lastSeenAtUtc,(commands||[]).map(command=>[command.commandId,command.status,command.deliveredAtUtc,command.startedAtUtc,command.completedAtUtc,command.resultCode,command.deliveryCount].join(':')).join('|'),(audit||[]).map(item=>[item.auditId,item.occurredAtUtc].join(':')).join('|')].join('||')}
          function updateCommandButtons(){const state=currentDetail?.runtime?.operationState||currentDevice?.operationState;$('disableProxy').disabled=commandCreateInFlight||state==='disabled';$('enableProxy').disabled=commandCreateInFlight||state==='enabled'}
          function renderDetail(device,detail,commands,audit=currentAudit){$('detailHostname').textContent=device.hostname;const meta=$('detailMeta');meta.replaceChildren();meta.append(badge(device.onlineState),badge(detail.runtime?.operationState||device.operationState),node('span','muted small','客户端 '+value(device.serviceVersion)));renderFreshness();renderHostPanel(device,detail);const agents=confirmedAgents(detail),suspected=(detail.agents||[]).filter(isSuspectedAgent);setText('detailAgentCount',agents.length);$('detailAgentNote').textContent=agents.filter(a=>a.running).length+' 个正在运行'+(suspected.length?' · '+suspected.length+' 个疑似':'');const grouped=groupAssets(detail),endpoints=grouped.flatMap(configurationEndpoints).filter(endpoint=>endpoint.isCurrent),models=unique(endpoints.map(endpoint=>String(endpoint.configuredModel||'').trim()));setText('detailEndpointCount',models.length);$('detailEndpointNote').textContent=endpoints.length+' 个当前配置关系 · '+(unique(grouped.filter(group=>configurationEndpoints(group).some(endpoint=>endpoint.isCurrent)).map(group=>familyLabel(group.family))).join(' · ')||'未发现当前配置');const activityById=new Map((detail.activity||[]).map(a=>[a.assetId,a])),activities=endpoints.map(endpoint=>activityForEndpoint(endpoint,activityById)).filter(Boolean),requests=activities.reduce((sum,a)=>sum+(a.requestCountSinceBoot||0),0),successes=activities.reduce((sum,a)=>sum+(a.successCountSinceBoot||0),0),failures=activities.reduce((sum,a)=>sum+(a.failureCountSinceBoot||0),0);setText('detailRequestCount',requests);$('detailRequestNote').textContent='成功 '+successes+' · 失败 '+failures;$('detailRequestNote').className='muted '+(failures?'bad-text':'');rememberInactiveOpenState();const groups=$('agentGroups');groups.replaceChildren();for(const group of grouped)groups.append(renderAgentGroup(group,activityById));renderSecondaryInfo(detail,commands,audit);updateCommandButtons()}
          async function fetchDetail(forceRender=false){if(detailFetchInFlight)return detailFetchInFlight;if(!currentDevice)return null;const id=currentDevice.deviceId,request=(async()=>{const [detail,commands,audit]=await Promise.all([api('/admin/v1/devices/'+id),api('/admin/v1/devices/'+id+'/commands'),api('/admin/v1/audit?deviceId='+encodeURIComponent(id)+'&skip=0&take=100')]);if(!currentDevice||currentDevice.deviceId!==id)return null;currentDetail=detail;currentCommands=commands;currentAudit=audit;currentDevice={...currentDevice,...detail.device};currentDevice.onlineState=onlineStateForDevice(currentDevice);lastDetailRefreshAt=new Date();const revision=detailRevision(detail,commands,audit),changed=revision!==lastDetailRevision;if(forceRender||changed){renderDetail(currentDevice,currentDetail,currentCommands,currentAudit);lastDetailRevision=revision}else renderFreshness();return changed})();detailFetchInFlight=request;try{return await request}finally{if(detailFetchInFlight===request)detailFetchInFlight=null}}
          function stopDetailAutoRefresh(){if(detailRefreshTimer!==null){clearInterval(detailRefreshTimer);detailRefreshTimer=null}}
          function startDetailAutoRefresh(){stopDetailAutoRefresh();if(!currentDevice||document.visibilityState!=='visible'||$('detailView').classList.contains('hidden'))return;detailRefreshTimer=setInterval(()=>{renderFreshness();fetchDetail().catch(error=>{if(error.status!==401&&error.status!==403)setAppMessage('详情自动刷新失败：'+error.message,true)})},DetailRefreshIntervalMilliseconds)}
          async function openDetail(device){if(detailFetchInFlight)return;stopDetailAutoRefresh();currentDevice=device;currentDetail=null;currentCommands=[];currentAudit=[];lastDetailRevision=null;lastDetailRefreshAt=null;inactiveOpenKeys.clear();setAppMessage('正在加载详情...');try{await fetchDetail(true);showDetailView();setAppMessage('');window.scrollTo({top:0,behavior:'smooth'})}catch(e){if(e.status!==401&&e.status!==403)setAppMessage('详情加载失败：'+e.message,true)}}
          async function refreshList(){setAppMessage('正在刷新...');try{await loadDevices();setAppMessage('已刷新')}catch(e){if(e.status!==401&&e.status!==403)setAppMessage('刷新失败：'+e.message,true)}}
          async function refreshCurrentDetail(){if(!currentDevice)return;setAppMessage('正在刷新详情...');try{await fetchDetail(true);setAppMessage('详情已刷新')}catch(e){if(e.status!==401&&e.status!==403)setAppMessage('详情刷新失败：'+e.message,true)}}
          async function createCommand(type){if(!currentDevice||commandCreateInFlight)return;const reason=prompt('请输入操作原因');if(!reason)return;const confirmed=prompt('请输入主机名 '+currentDevice.hostname+' 以确认');if(confirmed!==currentDevice.hostname){alert('主机名不匹配');return}const deviceId=currentDevice.deviceId;commandCreateInFlight=true;updateCommandButtons();setAppMessage('正在创建并确认命令...');try{const created=await api('/admin/v1/devices/'+deviceId+'/commands',{method:'POST',body:JSON.stringify({type,reason,expiresInMinutes:30})});if(!created?.commandId||String(created.deviceId).toLowerCase()!==String(deviceId).toLowerCase()||created.status!=='pending'){const error=new Error('POST 返回内容与当前终端或 Pending 状态不一致。');error.confirmationFailure=true;throw error}const commands=await api('/admin/v1/devices/'+deviceId+'/commands'),confirmedCommand=commands.find(command=>String(command.commandId).toLowerCase()===String(created.commandId).toLowerCase()&&String(command.deviceId).toLowerCase()===String(deviceId).toLowerCase());if(!confirmedCommand){const error=new Error('控制端接受了请求，但查询接口未返回同一 Command ID。');error.confirmationFailure=true;throw error}currentCommands=commands;setAppMessage('命令已创建并确认，Command ID：'+created.commandId);await Promise.all([loadDevices(),fetchDetail(true)]);if(currentDevice){const latest=devices.find(device=>device.deviceId===currentDevice.deviceId);if(latest){currentDevice={...currentDevice,...latest};renderDetail(currentDevice,currentDetail,currentCommands,currentAudit)}}}catch(e){if(e.status!==401&&e.status!==403){const prefix=e.status===409?'命令未创建：终端已有活动命令。':e.confirmationFailure?'命令创建结果未确认：':e.status?'命令创建被控制端拒绝：':'命令未发送或网络异常：';setAppMessage(prefix+e.message,true)}}finally{commandCreateInFlight=false;updateCommandButtons()}}
          document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')startDetailAutoRefresh();else stopDetailAutoRefresh()});$('authForm').onsubmit=e=>{e.preventDefault();connect()};$('allowlistForm').onsubmit=e=>{e.preventDefault();addAllowlistEntry()};$('saveAllowlist').onclick=saveAllowlist;$('reloadAllowlist').onclick=reloadAllowlist;$('refreshList').onclick=refreshList;$('search').oninput=renderDevices;$('state').onchange=renderDevices;$('backToList').onclick=()=>{showList();renderDevices();setAppMessage('')};$('refreshDetail').onclick=refreshCurrentDetail;$('disableProxy').onclick=()=>createCommand('disableProxy');$('enableProxy').onclick=()=>createCommand('enableProxy');if($('token').value&&$('actor').value)connect();else showLogin();
        </script></body></html>
        """;
}
